/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DatabaseManager;
import java.sql.SQLException;

/**
 *
 * @author rubenvde
 */
public class OnderwijseenheidView extends javax.swing.JFrame {

    /**
     * Creates new form OnderwijseenheidView2
     */
    public OnderwijseenheidView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_persoonsgegevens = new javax.swing.JLabel();
        jLabel_studiepunten = new javax.swing.JLabel();
        studiepunten = new javax.swing.JTextField();
        jLabel5_opleiding = new javax.swing.JLabel();
        jComboBox1_opleiding = new javax.swing.JComboBox();
        jLabel5_type = new javax.swing.JLabel();
        jComboBox1_type = new javax.swing.JComboBox();
        jLabel4_soortstudie = new javax.swing.JLabel();
        jLabel5_bedrijf = new javax.swing.JLabel();
        DatabaseManager dm = new DatabaseManager();
        jComboBox1_bedrijf = new javax.swing.JComboBox();
        jButton_toevoegen = new javax.swing.JButton();
        jButton_annuleren = new javax.swing.JButton();
        jComboBox1_soort_studie = new javax.swing.JComboBox();
        jLabel4_soortstudie2 = new javax.swing.JLabel();
        jComboBox1_periode = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1_persoonsgegevens.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1_persoonsgegevens.setText("Onderwijseenheid");

        jLabel_studiepunten.setText("Studiepunten");

        jLabel5_opleiding.setText("Opleiding");

        try{
            String [] opleidingen = new String[dm.getOpleidingNamen().size()];
            for(int i = 0; i < opleidingen.length; i++){
                opleidingen[i] = dm.getOpleidingNamen().get(i);
                jComboBox1_opleiding.addItem(opleidingen[i]);
            }

            /*
            for(int i = 0; i < opleidingen.length; i++){
                jComboBox1_type.addItem(opleidingen[i]);
            }
            */

        }catch(SQLException e){
            System.out.println("Fout bij combobox opleiding van Binnenlandse StudentView.");
            e.printStackTrace();
        }
        /*
        jComboBox1_opleiding.setModel(new javax.swing.DefaultComboBoxModel(opleidingen));
        */
        jComboBox1_opleiding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_opleidingActionPerformed(evt);
            }
        });

        jLabel5_type.setText("Type");

        jComboBox1_type.addItem("Leeg");
        jComboBox1_type.addItem("Studie");
        jComboBox1_type.addItem("Stage");

        jComboBox1_soort_studie.setEnabled(false);
        jComboBox1_bedrijf.setEnabled(false);
        /*
        for(int i = 0; i < opleidingen.length; i++){
            jComboBox1_type.addItem(opleidingen[i]);
        }
        */
        /*
        jComboBox1_type.setModel(new javax.swing.DefaultComboBoxModel(opleidingen));
        */
        jComboBox1_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_typeActionPerformed(evt);
            }
        });

        jLabel4_soortstudie.setText("Soort studie");

        jLabel5_bedrijf.setText("Bedrijf");

        try{
            String [] bedrijven = new String[dm.getBedrijfsNamen().size()];
            for(int i = 0; i < bedrijven.length; i++){
                bedrijven[i] = dm.getBedrijfsNamen().get(i);
                jComboBox1_bedrijf.addItem(bedrijven[i]);
            }

            /*
            for(int i = 0; i < opleidingen.length; i++){
                jComboBox1_type.addItem(opleidingen[i]);
            }
            */

        }catch(SQLException e){
            System.out.println("Fout bij combobox opleiding van Binnenlandse StudentView.");
            e.printStackTrace();
        }
        /*
        jComboBox1_bedrijf.setModel(new javax.swing.DefaultComboBoxModel(opleidingen));
        */
        jComboBox1_bedrijf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_bedrijfActionPerformed(evt);
            }
        });

        jButton_toevoegen.setText("Toevoegen");
        jButton_toevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_toevoegenActionPerformed(evt);
            }
        });

        jButton_annuleren.setText("Annuleren");
        jButton_annuleren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_annulerenActionPerformed(evt);
            }
        });

        jComboBox1_soort_studie.addItem("Minors");
        jComboBox1_soort_studie.addItem("European Project Semesters");
        jComboBox1_soort_studie.addItem("Summer schools");

        /*
        for(int i = 0; i < opleidingen.length; i++){
            jComboBox1_type.addItem(opleidingen[i]);
        }
        */
        /*
        jComboBox1_soort_studie.setModel(new javax.swing.DefaultComboBoxModel(opleidingen));
        */
        jComboBox1_soort_studie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_soort_studieActionPerformed(evt);
            }
        });

        jLabel4_soortstudie2.setText("Periode");

        try{
            String [] periodes = new String[dm.getPeriodes().size()];
            for(int i = 0; i < periodes.length; i++){
                periodes[i] = dm.getPeriodes().get(i);
                jComboBox1_periode.addItem(periodes[i]);
            }

        }catch(SQLException e){
            System.out.println("Fout bij combobox periode van Onderwijseenheid.");
            e.printStackTrace();
        }
        /*
        jComboBox1_periode.setModel(new javax.swing.DefaultComboBoxModel(opleidingen));
        */
        jComboBox1_periode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_periodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1_persoonsgegevens)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel5_type, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBox1_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4_soortstudie2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBox1_periode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel5_opleiding, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBox1_opleiding, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel_studiepunten, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(studiepunten, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton_toevoegen)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_annuleren))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4_soortstudie, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5_bedrijf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox1_soort_studie, 0, 200, Short.MAX_VALUE)
                                .addComponent(jComboBox1_bedrijf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_persoonsgegevens, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_studiepunten, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studiepunten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1_opleiding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5_opleiding, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4_soortstudie2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1_periode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5_type, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4_soortstudie, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1_soort_studie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1_bedrijf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5_bedrijf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_annuleren)
                    .addComponent(jButton_toevoegen))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1_opleidingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_opleidingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1_opleidingActionPerformed

    private void jComboBox1_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_typeActionPerformed
        String gekozenoptie = jComboBox1_type.getSelectedItem().toString();
        switch(gekozenoptie) {
            case "Studie":
                jComboBox1_soort_studie.setEnabled(true);
                jComboBox1_bedrijf.setEnabled(false);
                break;
            case "Stage":
                jComboBox1_soort_studie.setEnabled(false);
                jComboBox1_bedrijf.setEnabled(true);
                break;
            default:
                jComboBox1_soort_studie.setEnabled(false);
                jComboBox1_bedrijf.setEnabled(false);
                break;
        }
    }//GEN-LAST:event_jComboBox1_typeActionPerformed

    private void jComboBox1_bedrijfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_bedrijfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1_bedrijfActionPerformed

    private void jButton_toevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_toevoegenActionPerformed
        /*
        char geslacht = '?';
        if(jRadioButton_man.isSelected()){geslacht = 'M';}else if(jRadioButton_vrouw.isSelected()){geslacht = 'V';}

        if(this.studentType){   //Toevoegen binnenlands student

            if(alleVakkenControleren(studentType)){

                Entiteit binnenStudent;
                dm = new DatabaseManager();

                try {

                    if(!knopType){
                        binnenStudent = new BinnenlandseStudent(studiepunten.getText(), naam.getText(), geslacht,
                            soort_studie.getText(), telnr1.getText(), telnr2.getText(), universiteit.getText(), opleidingId);

                        dm.insertEntity(binnenStudent);
                        JOptionPane.showMessageDialog(null, "Met succes toegevoegd.");
                    }else{
                        binnenStudent = new BinnenlandseStudent(studiepunten.getText(), naam.getText(), geslacht,
                            soort_studie.getText(), telnr1.getText(), telnr2.getText(), universiteit.getText(), dm.getOpleidingID("" + jComboBox1_type.getSelectedItem()));

                        dm.updateEntity(binnenStudent);
                        JOptionPane.showMessageDialog(null, "Met succes gewijzigd.");
                    }
                } catch (SQLException ex) {
                    System.out.println("Student is niet gewijzigd of toegevoegd in database!");
                    ex.printStackTrace();
                }
                this.dispose();
            }else{
                System.out.println("Binnenlandse student toevoegen en wijzigen werkt niet. Zie StudentView.");
            }

        }else{  //toevoegen buitenlands student

            if(alleVakkenControleren(studentType)){
                Entiteit buitenlandseStudent = new BuitenlandseStudent(studiepunten.getText(), naam.getText(), geslacht, soort_studie.getText(), telnr1.getText(), telnr2.getText(), adres.getText(), land.getText(), universiteit.getText());

                dm = new DatabaseManager();

                try {
                    if(knopType){
                        System.out.println("updaterecord erin! Buiten"); // Wijzigen student
                        dm.updateEntity(buitenlandseStudent);
                        JOptionPane.showMessageDialog(null, "Met succes gewijzigd.");
                    }else{
                        System.out.println("addrecord erin! Buiten");
                        dm.insertEntity(buitenlandseStudent);
                        JOptionPane.showMessageDialog(null, "Met succes toegevoegd.");
                    }
                } catch (SQLException ex) {
                    System.out.println("Student is niet toegevoegd in database!");
                    ex.printStackTrace();
                }

                this.dispose();
            }else{
                System.out.println("Buitenlandse student toevoegen en wijzigen werkt niet. Zie StudentView.");
            }
        }
        */
        //hv.getRefreshJTable();
    }//GEN-LAST:event_jButton_toevoegenActionPerformed

    private void jButton_annulerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_annulerenActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_annulerenActionPerformed

    private void jComboBox1_soort_studieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_soort_studieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1_soort_studieActionPerformed

    private void jComboBox1_periodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_periodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1_periodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OnderwijseenheidView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OnderwijseenheidView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OnderwijseenheidView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OnderwijseenheidView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OnderwijseenheidView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_annuleren;
    private javax.swing.JButton jButton_toevoegen;
    private javax.swing.JComboBox jComboBox1_bedrijf;
    private javax.swing.JComboBox jComboBox1_opleiding;
    private javax.swing.JComboBox jComboBox1_periode;
    private javax.swing.JComboBox jComboBox1_soort_studie;
    private javax.swing.JComboBox jComboBox1_type;
    private javax.swing.JLabel jLabel1_persoonsgegevens;
    private javax.swing.JLabel jLabel4_soortstudie;
    private javax.swing.JLabel jLabel4_soortstudie2;
    private javax.swing.JLabel jLabel5_bedrijf;
    private javax.swing.JLabel jLabel5_opleiding;
    private javax.swing.JLabel jLabel5_type;
    private javax.swing.JLabel jLabel_studiepunten;
    private javax.swing.JTextField studiepunten;
    // End of variables declaration//GEN-END:variables
}
