/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import Controller.DatabaseManager;
import Model.Opleiding;
import Model.Entiteit;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JTable;

/**
 *
 * @author Ruben
 */
public class OpleidingView extends javax.swing.JFrame {
    
    private DatabaseManager dm;
    private HoofdView hv;
    private int contactpersoonId;
    private int opleidingId;
    private boolean wijzigen;
    
    
    /**
     * Creates new form OpleidingView
     */
    public OpleidingView(HoofdView hv) {
        super("Nieuwe opleiding");
        this.contactpersoonId = 0;
        this.hv = hv;
        dm = new DatabaseManager();
        this.wijzigen = false;
        this.opleidingId = 0;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_periodegegevens = new javax.swing.JLabel();
        naamOpleiding = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        toevoegenKnop = new javax.swing.JButton();
        annulerenKnop = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_contactpersonen = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1_periodegegevens.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1_periodegegevens.setText("Opleidinggegevens");

        jLabel1.setText("Naam opleiding");

        toevoegenKnop.setText("Toevoegen");
        toevoegenKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toevoegenKnopActionPerformed(evt);
            }
        });

        annulerenKnop.setText("Annuleren");
        annulerenKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerenKnopActionPerformed(evt);
            }
        });

        jLabel2.setText("Contactpersoon");

        try{
            ArrayList<String> contactNamen = new ArrayList<String>(dm.getContactpersoonNamen());
            String [] namen = new String[contactNamen.size()];
            namen = contactNamen.toArray(namen);
            for(int i = 0; i < namen.length; i++){
                jComboBox_contactpersonen.addItem(namen[i]);
            }
            jComboBox_contactpersonen.setSelectedIndex(0);
        }catch(SQLException e){
            e.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(53, Short.MAX_VALUE)
                        .addComponent(toevoegenKnop)
                        .addGap(18, 18, 18)
                        .addComponent(annulerenKnop))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1_periodegegevens)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(naamOpleiding)
                                    .addComponent(jComboBox_contactpersonen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_periodegegevens, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(naamOpleiding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_contactpersonen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toevoegenKnop)
                    .addComponent(annulerenKnop))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annulerenKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerenKnopActionPerformed
        this.dispose();
    }//GEN-LAST:event_annulerenKnopActionPerformed

    private void toevoegenKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toevoegenKnopActionPerformed
        try {
            contactpersoonId = dm.getContactpersoonID("" + jComboBox_contactpersonen.getSelectedItem());
            System.out.println("ContactId: " + contactpersoonId);
        } catch (SQLException e) {
            System.out.println("Check rij 141.");
            e.printStackTrace();
        }
        
        if(alleVakkenControleren()){
            JOptionPane.showMessageDialog(null, "Alle vakken moeten ingevuld worden.");
        }else{
            Entiteit opleiding = new Opleiding(opleidingId, contactpersoonId, naamOpleiding.getText());
            try {
                if(!wijzigen){
                    dm.insertEntity(opleiding);
                    JOptionPane.showMessageDialog(null, "Met succes toegevoegd.");
                }else if(wijzigen){
                    dm.updateEntity(opleiding);
                    JOptionPane.showMessageDialog(null, "Met succes gewijzigd.");
                }
            } catch (SQLException e) {
                System.out.println("Fout bij toevoegen opleiding, zie opleidingView");
                e.printStackTrace();
            } finally{
                this.dispose();
            }
        }
        hv.getRefreshJTable();
    }//GEN-LAST:event_toevoegenKnopActionPerformed

    /**
     * @param args the command line arguments
     */
    private boolean alleVakkenControleren(){
        return this.naamOpleiding.getText().isEmpty();
    }
    
    public void opleidingWijzigen(boolean wijzigen, JTable table){
        this.wijzigen = wijzigen;
        this.toevoegenKnop.setText("Wijzigen");
        this.setTitle("Wijzigen opleiding");
        try {
            String naam = "" + table.getValueAt(table.getSelectedRow(), table.getSelectedColumn());
            
            for (int i = 0; i < table.getColumnCount(); i++) {
                String contactNaam = "" + table.getValueAt(table.getSelectedRow(), i);
                if(contactNaam.equals("" + jComboBox_contactpersonen.getItemAt(i))){
                    jComboBox_contactpersonen.setSelectedIndex(i);
                }
            }
        
            naamOpleiding.setText(naam);
            opleidingId = dm.getOpleidingID(naam);
        } catch (SQLException e) {
            System.out.println("Zie opleidingWijzigen methode");
            e.printStackTrace();
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpleidingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpleidingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpleidingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpleidingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                //new OpleidingView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerenKnop;
    private javax.swing.JComboBox jComboBox_contactpersonen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_periodegegevens;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField naamOpleiding;
    private javax.swing.JButton toevoegenKnop;
    // End of variables declaration//GEN-END:variables
}
